project:
  type: website

website:
  title: "PM 566 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Final-Report.qmd
        text: Download the Report

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

